import os
from google import genai
from google.genai import types

def adjudicate_conflict(image_path, candidates):
    """Sends the image and conflicting strings to Gemini for selection."""
    
    # Grab the API key from the environment
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable not set. Please export it.")
        return None
        
    # The new SDK uses a centralized Client object
    client = genai.Client(api_key=api_key)
    
    # Read the cropped image as bytes
    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
    except Exception as e:
        print(f"Error loading image: {e}")
        return None

    # The strict guardrail prompt
    system_instruction = (
        "You are an expert in reading degraded 19th-century Rabbinic Hebrew typography. "
        "You will be provided with an image of a single cropped word, and a JSON array of candidate strings generated by OCR engines. "
        "Your task is to select the candidate string that perfectly matches the image. "
        "You must output ONLY the exact matching string from the candidate list. Do not invent text. "
        "If none of the candidates match, output 'NULL'."
    )
    
    print(f"Sending image and candidates {candidates} to Gemini...")
    
    try:
        # Use the modern API call structure with the required Part types
        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=[
                types.Part.from_text(text=f"Candidates: {candidates}"),
                types.Part.from_bytes(data=image_bytes, mime_type="image/png")
            ],
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.0 # Strict determinism
            )
        )
        result = response.text.strip()
        print(f"Model successfully selected: {result}")
        return result
        
    except Exception as e:
        print(f"API Error: {e}")
        return None

if __name__ == "__main__":
    # The conflict from our earlier test sample:
    # Base (Berlin): 'ליה' | Witness (Przemyśl Google): 'ליס'
    test_candidates = '["ליה", "ליס"]'
    
    # Run the test on the cropped image
    adjudicate_conflict("test_crop.png", test_candidates)
