#!/usr/bin/env python3
"""
pipeline/build_structural_defect_report.py

Stage 4e. Runs the three STRUCTURAL corpus detectors on every rebuild and writes
`structural_defect_report.json` - a triage queue for a human, never a fix list.

WHY THIS EXISTS. `tools/detect_repeated_words.py`,
`tools/detect_ligature_corruption.py` and `tools/detect_split_merge.py` were in
no chain and wrote no artifact, so their findings existed only while somebody
watched a terminal. Measured 2026-09-07: 18 flagged positions no reviewer could
see by any route - among them `אאמוראי` in klalim 130 and 168, which is the
alef-lamed ligature fused with the FOLLOWING word, a defect class the vision
adjudicator cannot find because it is upstream of every reader (Lesson 24).

This is Lesson 32 applied to the three detectors the lesson itself did not
reach. `build_lexical_defect_report.py` did exactly this for the other two on
2026-08-26, after the reviewer hand-repaired a word in klal 84 that a detector
had been correctly reporting to stdout all along. Same fix, same reasoning,
three tools later. All three run in well under a second on the full corpus, so
there is no cost argument.

WHAT THIS DELIBERATELY DOES NOT DO, and it is the same boundary
`build_lexical_defect_report.py` holds: it writes no `klal_flag` rows and folds
nothing into the review queue. The ledger is append-only and permanent, and
these detectors carry real false positives - klal 144's `ז`+`ה` -> `זה` is a
list of Hebrew NUMERALS being read as a word, and the repeated-word detector
cannot tell a scribal repetition from an OCR one. Promoting an entry from this
report to a flag stays a deliberate, separate act.

Merging a tier of this into the dashboard queue, the way
`assemble_corrections_dataset.merge_lexical_defects()` does for the lexical
report, is available at any time and costs nothing to reverse: it is a derived
source, regenerated by every rebuild, with no residue in the ledger. It is not
done here because nobody has yet measured a precision tier for these three.
"""
import argparse
import collections
import datetime
import json
import os
import sys

# The sys.path bootstrap is unavoidable - corpus_io cannot be imported before
# `pipeline/` is importable - but it is the ONLY use of a locally-derived root
# here. Every data path below comes from cio.repo_path(), so this file is not a
# 48th bypass of the corpus-root seam (item 0BI, pinned by
# test_the_corpus_root_bypass_count_has_not_grown).
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
sys.path.insert(0, os.path.join(os.path.dirname(_HERE), "tools"))

import corpus_io as cio  # noqa: E402
import detect_repeated_words as rep  # noqa: E402
import detect_ligature_corruption as lig  # noqa: E402
import detect_split_merge as sm  # noqa: E402

ALEPH_BET = "אבגדהוזחטיכלמנסעפצקרשת"

OUT_PATH = cio.repo_path("structural_defect_report.json")
ACK_PATH = cio.repo_path("structural_defect_acknowledged.json")


def _key(row, occurrence=0):
    """The identity an acknowledgement is recorded against.

    (klal, detector, stored) - deliberately NOT word_index. An index moves every
    time an earlier edit changes the klal's word count, and an acknowledgement
    that evaporates on an unrelated edit is worse than none: the finding returns
    looking new, and the reviewer re-checks work they already did.

    `stored` IS in the key, and that is the other half. Acknowledging says "this
    text, here, is correct as printed" - so if the text changes, the
    acknowledgement no longer applies and the finding correctly comes back.

    PLUS AN OCCURRENCE ORDINAL - item 0DE finding 7, added 2026-09-08. Those
    three fields are not unique WITHIN a klal: two `repeated_word` findings on
    the same word, or a second wrong `ה` in one enumeration, collapse to one key,
    so acknowledging the first silently suppresses the second - unreviewed, and
    with nothing on screen saying a second existed. This is the same address
    shape item 0BB settled on for rulings: the bare word names one of several,
    `(word, occurrence)` names one.

    The ordinal is assigned by word_index order within its (klal, detector,
    stored) group, so it survives a uniform index shift - every index in the klal
    moves together and the order is preserved. It changes only when a finding is
    inserted or removed between two others, which is exactly when the later ones
    deserve another look.

    OCCURRENCE 0 CARRIES NO SUFFIX, deliberately: every key in
    `structural_defect_acknowledged.json` today is a first occurrence (22 rows,
    22 distinct keys, checked), so this change invalidates none of the 20
    acknowledgements already recorded. A migration that quietly re-opened work
    the reviewer had finished would be a worse bug than the one being fixed.
    """
    base = f"{row['klal_id']}|{row['detector']}|{row['stored']}"
    return base if not occurrence else f"{base}|#{occurrence + 1}"


def _keys_for(rows):
    """{id(row): key} with each row's occurrence ordinal resolved. See _key()."""
    seen = {}
    out = {}
    for r in sorted(rows, key=lambda r: (r["klal_id"], r["detector"],
                                         r["stored"], r["word_index"])):
        base = (r["klal_id"], r["detector"], r["stored"])
        n = seen.get(base, 0)
        seen[base] = n + 1
        out[id(r)] = _key(r, n)
    return out


def load_acknowledged():
    return {e["key"]: e for e in (cio.load_json(ACK_PATH, default=[]) or [])}


def build(part_path=None):
    """[{klal_id, word_index, stored, proposal, detector, evidence}], sorted.

    Every tuple is unpacked at its declared arity rather than with a `*rest`
    catch-all: these four return four DIFFERENT shapes, and a positional guess
    is how the sibling report ended up with an `isinstance(x, str)` scan to find
    its own fields. If a detector's shape changes, this should fail loudly here.
    """
    part_path = part_path or cio.PART1_PATH
    klal_words = cio.load_klal_words(part_path)
    rows = []

    for kid, wi, word, _next_word in rep.find_repeated_words(klal_words):
        rows.append({"klal_id": kid, "word_index": wi, "stored": word,
                     "proposal": None, "detector": "repeated_word",
                     "evidence": "this word and the next are identical"})

    # Only the COMPOUND form. find_candidates() is the plain dropped-lamed
    # sweep, and those reach a reviewer through the queue's own ligature
    # handling; the compound case is the one nothing else looks for, because the
    # ligature swallowed the space and the corrupt token is not a word the
    # lexicon or the vision adjudicator can be asked about.
    counts = lig.build_frequency_table(klal_words)
    for kid, wi, stored, left, right, n in lig.find_compound_candidates(klal_words, counts):
        rows.append({"klal_id": kid, "word_index": wi, "stored": stored,
                     "proposal": f"{left} {right}", "detector": "ligature_compound",
                     "evidence": f"an `אלא` ligature fused with the following word; "
                                 f"`{right}` occurs {n}x independently"})

    # ENUMERATION RUNS. Added 2026-09-07 after the reviewer found klal 144's
    # `א ב ג ד ה ו ז ה ט ו` and asked what the ink said.
    #
    # WHY THIS IS THE SHARPEST CHECK IN THIS FILE. Every other detector here
    # argues from frequency, which is evidence. An enumeration argues from
    # SEQUENCE, which is closer to proof: the eighth item in a list that opens
    # `א ב ג ד ה ו ז` can only be `ח`. Confirmed against the scan on the case
    # that prompted it - page 52's right margin carries ten markers, and DocAI
    # read the 8th `ח` as `ה` and the 10th `י` as `ו`, both plain misreads of
    # letters the sequence already determined.
    #
    # The run itself is ALSO a structural defect independent of the letters, and
    # this cannot see that half: those ten markers are a COLUMN down the right
    # margin (x 0.87-0.89, y 0.26-0.77) heading ten separate items, and the
    # extraction flattened them into one contiguous inline blob mid-sentence.
    # See item 0CY - fixing that is an extraction change, not a text ruling.
    for kid, words in klal_words.items():
        run = []
        for i, word in enumerate(words + [""]):
            if len(cio.hebrew_letters_only(word)) == 1:
                run.append((i, cio.hebrew_letters_only(word)))
                continue
            if len(run) >= 4:
                seq = "".join(c for _, c in run)
                # ANCHOR ON THE RUN'S OWN FIRST LETTER, NOT ON א - item 0DE
                # finding 6, fixed 2026-09-08.
                #
                # `ideal = ALEPH_BET[:len(seq)]` asserted that every run of four
                # or more single letters is a list STARTING at א. A list that
                # continues from an earlier klal or an earlier column - `ד ה ו ז`
                # - then mismatches at every position and is reported as four
                # separate breaks, each with a confident single-letter proposal.
                # Anchoring on the first letter scores the sequence that is
                # actually there. A run that does start at א is unchanged, which
                # is why klal 144's two findings survive this: they are TRUE
                # positives, confirmed against page 52 in this function's own
                # header comment.
                #
                # The tradeoff, stated rather than hidden: if the FIRST letter is
                # itself a misread, the anchor is wrong and everything after it
                # scores against the wrong ideal. That is strictly better than
                # today's behaviour, which is that same failure for every run not
                # starting at א, but it is not free - which is why this detector
                # writes a triage report and never a flag.
                #
                # AND IT IS BOUNDS-CHECKED. `ALEPH_BET` is 22 letters and
                # `range(len(seq))` was not capped, so a run of 23+ single-letter
                # tokens raised IndexError and aborted stage 4e of the rebuild -
                # on text that changes every time a correction lands.
                start = ALEPH_BET.find(run[0][1])
                if start == -1 or start + len(seq) > len(ALEPH_BET):
                    run = []
                    continue
                ideal = ALEPH_BET[start:start + len(seq)]
                if seq != ideal:
                    bad = [(run[j][0], run[j][1], ideal[j])
                           for j in range(len(seq)) if seq[j] != ideal[j]]
                    for wi, got, want in bad:
                        rows.append({
                            "klal_id": kid, "word_index": wi, "stored": got,
                            "proposal": want, "detector": "enumeration_break",
                            "evidence": f"item {wi - run[0][0] + 1} of a {len(seq)}-item "
                                        f"enumeration starting at w{run[0][0]} with "
                                        f"{run[0][1]}: the sequence reads {seq} where a "
                                        f"consecutive list from {run[0][1]} requires {ideal}"})
            run = []

    indep = sm.load_independent_frequency()
    if indep:
        # THE DETECTOR'S OWN COUNTING CONVENTION, not a re-derivation: built from
        # clean_text, skipping gershayim forms (detect_split_merge.main's comment
        # explains why - counting inside a narrower field makes every word a
        # hapax and the rare-form gate stops gating).
        own = collections.Counter()
        # `klal_words`, not a second cio.load_klal_words(part_path) - same file,
        # same call, already loaded at the top of this function (0DE finding 8).
        for words in klal_words.values():
            for w in words:
                if not cio.has_gershayim(w):
                    own[w] += 1
        for kid, wi, w, left, right, lf, rf in sm.find_merge_candidates(klal_words, own, indep):
            rows.append({"klal_id": kid, "word_index": wi, "stored": w,
                         "proposal": f"{left} {right}", "detector": "merge",
                         "evidence": f"splits into two independently common words "
                                     f"({lf}x / {rf}x)"})
        for kid, wi, w1, w2, joined, freq in sm.find_split_candidates(klal_words, own, indep):
            rows.append({"klal_id": kid, "word_index": wi, "stored": f"{w1} {w2}",
                         "proposal": joined, "detector": "split",
                         "evidence": f"joins with the next token into `{joined}`, {freq}x independently"})
    else:
        # Never emit a short report that reads as "nothing found" when the input
        # was missing (Lesson 26 - a wrong suppression is silent).
        print("  WARNING: sefaria_reference_corpus not present - the split/merge "
              "detector was SKIPPED, not clean. See SETUP.md.")

    rows.sort(key=lambda r: (r["klal_id"], r["word_index"], r["detector"]))
    ack = load_acknowledged()
    keys = _keys_for(rows)
    for r in rows:
        hit = ack.get(keys[id(r)])
        r["acknowledged"] = bool(hit)
        if hit:
            r["acknowledged_on"] = hit.get("ts")
            r["acknowledged_note"] = hit.get("note")
    return rows


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--acknowledge-all", action="store_true",
                    help="record every CURRENT finding as checked-and-correct, so it stops "
                         "being reported. A finding comes back if its text changes.")
    ap.add_argument("--note", default="checked against the scan and correct as printed",
                    help="why these are being dismissed - stored with each acknowledgement")
    args = ap.parse_args()

    rows = build()
    if args.acknowledge_all:
        ack = load_acknowledged()
        stamp = datetime.datetime.now(datetime.timezone.utc).isoformat()
        added = 0
        keys = _keys_for(rows)
        for r in rows:
            k = keys[id(r)]
            if k in ack:
                continue
            ack[k] = {"key": k, "ts": stamp, "note": args.note,
                      "klal_id": r["klal_id"], "detector": r["detector"], "stored": r["stored"]}
            added += 1
        with open(ACK_PATH, "w", encoding="utf-8") as f:
            json.dump(sorted(ack.values(), key=lambda e: (e["klal_id"], e["detector"])),
                      f, ensure_ascii=False, indent=2)
            f.flush()
        print(f"Acknowledged {added} finding(s); {len(ack)} on record in {ACK_PATH}")
        rows = build()

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)
        f.flush()

    new = [r for r in rows if not r["acknowledged"]]
    by = collections.Counter(r["detector"] for r in new)
    print(f"Wrote {OUT_PATH}: {len(rows)} structural candidate(s), "
          f"{len(rows) - len(new)} previously acknowledged")
    # THE COUNT THAT MATTERS IS THE NEW ONE. A report that prints the same 20
    # dismissed findings every run trains its reader to skip it, and the next
    # real defect arrives inside that noise - which is how a detector with
    # correct output delivers nothing (Lesson 32's own failure mode, one level
    # on). Acknowledged findings stay IN the file, so nothing is hidden; they
    # just stop being announced.
    if not new:
        print("  0 NEW - every current finding has been checked and dismissed.")
    else:
        print(f"  {len(new)} NEW, unchecked:")
        for k, n in by.most_common():
            print(f"    {n:>4}  {k}")
        for r in new[:10]:
            print(f"       klal {r['klal_id']:>4} w{r['word_index']:<5} {r['stored']!r}"
                  f" -> {r['proposal']!r}")
    print("  A TRIAGE QUEUE, not a fix list - these carry real false positives "
          "and none of them is flagged to a reviewer.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
