#!/usr/bin/env python3
"""
tools/detect_root_entries.py

Find the entry headings of a root-dictionary, where each entry is headed by its
root SPELLED OUT AS LETTER NAMES.

THE STRUCTURE THIS EXISTS FOR. Sefer HaShorashim (Ibn Janah, tr. Ibn Tibbon, ed.
Bacher, Berlin 1896) has no gematria marker and no numbered sections, so
`pipeline/build_gematria_trace.py` has no analogue here. What it has instead is
better: every entry opens with its root written out as the NAMES of its letters,
terminated by a period -

    הבית והצדי והקוף.      = ב-צ-ק
    הבית והצדי והריש.      = ב-צ-ר

That is a closed 22-word vocabulary, so it is cheaper to detect than a gematria
marker. It is also SELF-CHECKING in a way a marker is not: the names spell the
root, and a dictionary's roots run in alphabetical order, so the detector's own
output can be validated against a rule the book must obey. `--check-order`
reports every position where the sequence goes backwards, and those are either a
missed heading, a false heading, or a genuine printing irregularity - all three
worth a human look, which is why it reports rather than repairs.

WHAT IT READS. Any directory of per-page plain text - by default the recovered
PDF text layer from `tools/extract_pdf_text_layer.py`, which for this book is
1,094,298 Hebrew characters over 636 pages at no API cost. That layer is Google
OCR and carries Google OCR's errors, so a heading it garbles is invisible here;
the order check is what surfaces the resulting gap.

ON OCR VARIANTS. `צרי` is accepted for `צדי` because the ד/ר confusion is this
printing's most common sort-level failure and it was observed in the layer on a
page whose ink was read directly. Variants are listed explicitly, never
generated by fuzzy matching: a fuzzy letter-name matcher would accept ordinary
running text that happens to be one edit away, and Lesson 5 (FUZZY IS NOT A
POSITION) is exactly about not doing that for a structural anchor.

Usage:
  python3 tools/detect_root_entries.py --layer-dir ~/work/hashorashim/google_books_layer
  python3 tools/detect_root_entries.py --layer-dir ... --check-order --out entries.json
"""

import argparse
import collections
import json
import os
import re
import sys

# Bootstrap only - deliberately NOT bound to a name like REPO, which is the
# seam bypass tests/test_pipeline_logic.py's bypass guard exists to catch. Every
# real path below goes through corpus_io, which resolves $SEFER_CORPUS_ROOT at
# call time.
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(os.path.dirname(_HERE), "pipeline"))
import corpus_io as cio  # noqa: E402

# The 22 letter names as this edition spells them, plus OCR variants ACTUALLY
# OBSERVED in the layer. Adding a variant is a claim about the printing; make it
# only after seeing it, and say which sort produced it.
# DISCOVERED FROM THE DATA, not written from knowledge of the alphabet. A
# hand-written list of the "obvious" 22 names found 840 headings and MISSED
# 1,147 - it had `ריש` for resh where this edition prints `רש`, so the entire
# ר מאמר (30 pages, PDF 509-538) came back empty and the alphabetical-order
# check did not notice, because a whole missing section produces no local
# inversion (ק -> ש is still forward). That is Lesson 26 THE FILTER THAT HIDES:
# the failure was silence, and the guard could not see it.
#
# These counts come from clustering every line-initial heading-SHAPED line in
# the recovered layer. Variants are kept separate from spellings on purpose:
LETTER_NAMES = {
    # the edition's own spellings
    "אלף": "א", "בית": "ב", "גימל": "ג", "דלת": "ד", "הא": "ה",
    "ואו": "ו", "זין": "ז", "חית": "ח", "טית": "ט", "יוד": "י",
    "כף": "כ", "למד": "ל", "מם": "מ", "נון": "נ", "סמך": "ס",
    "עין": "ע", "פא": "פ", "צדי": "צ", "קוף": "ק", "רש": "ר",
    "שין": "ש", "תו": "ת",
    # further spellings the edition itself uses, both attested in the layer
    "ריש": "ר", "תיו": "ת", "ויו": "ו", "וו": "ו", "חת": "ח", "טת": "ט",
    # OCR variants, each with the sort that produced it
    "צרי": "צ",    # ד -> ר, this printing's commonest sort-level confusion
    "נימל": "ג",   # ג -> נ
}
# "the doubled one" - a geminate root, repeating the letter before it:
# `הרש וההא הכפולה` is ר-ה-ה. 152 occurrences; without it those entries are lost.
DOUBLED = "כפולה"

ALEPHBET = "אבגדהוזחטיכלמנסעפצקרשת"

def _spaced(name):
    r"""`פא` -> `פ\s*א`. DocAI sometimes splits a letter-name across a space
    (`והפ א` for `והפא` on p135), which is tokenizer noise, not a different
    reading - the ink says `והפא`. Tolerating an internal space recovers those
    without loosening the three guards that actually carry the anchor: the match
    is still line-initial, still terminated, and still drawn from a closed
    22-word vocabulary."""
    return r"\s*".join(name)


_NAME_ALT = "|".join(_spaced(n) for n in sorted(LETTER_NAMES, key=len, reverse=True))
# A heading is LINE-INITIAL and ends with a period or comma. Both halves matter:
# the same letter-name words appear constantly inside running prose (the book is
# about letters), and only the line-initial + terminator shape is the heading.
#
# "Line-initial" means THE FIRST HEBREW LETTER ON THE LINE, not the first
# character. Widened 2026-09-09 after the DocAI stream lost 21 of 308 headings in
# the א-ב-ג slice that the PDF text layer found - every one of them real, and
# every one preceded by a footnote numeral or a bracket that the two OCRs place
# differently:
#     p59    17 האלף והבית והכף . ויתאבכו גאות עשן
#     p109   88 הבית והזין הכפולה , בחזו להם ישראל
#     p146   [ הנימל והעין וההא , יגעה שור
# The anchor is not weakened by this: the first Hebrew letter must still open the
# heading, the terminator is still required, and the letter-name vocabulary is
# still closed.
HEADING = re.compile(
    rf"^[^\u05d0-\u05ea]*ה(?P<first>{_NAME_ALT})(?P<rest>(?:\s+ו?ה(?:{_NAME_ALT}|{DOUBLED})){{1,4}})\s*[.,]"
)
NAME_IN_REST = re.compile(rf"ו?ה({_NAME_ALT}|{DOUBLED})")


def match_heading(line):
    """(root, end_offset) for a heading line, or None.

    The END OFFSET matters: headings terminate with a period OR a comma, and
    splitting on `line.find(".")` instead swallows the whole entry into the title
    whenever the terminator is a comma. That produced 8 empty entries out of 299
    on the first build - `האלף והנימל , אבל זה הוא...` kept everything.
    """
    m = HEADING.match(line)
    if not m:
        return None
    root = _letters_from(m)
    return (root, m.end()) if root else None


def parse_heading(line):
    m = HEADING.match(line)
    if not m:
        return None
    return _letters_from(m)


def _letters_from(m):
    squash = lambda x: re.sub(r"\s+", "", x)
    letters = [LETTER_NAMES[squash(m.group("first"))]]
    for n in NAME_IN_REST.findall(m.group("rest")):
        if squash(n) == DOUBLED:
            if not letters:
                return None
            letters.append(letters[-1])   # geminate: repeat the preceding letter
        else:
            letters.append(LETTER_NAMES[squash(n)])
    return "".join(letters)


def scan(layer_dir):
    entries = []
    pages = sorted(
        (int(re.search(r"page_(\d+)\.txt$", f).group(1)), os.path.join(layer_dir, f))
        for f in os.listdir(layer_dir) if re.match(r"page_\d+\.txt$", f))
    for page, path in pages:
        with open(path, encoding="utf-8") as fh:
            for lineno, line in enumerate(fh.read().split("\n"), start=1):
                root = parse_heading(line)
                if root:
                    entries.append({"page": page, "line": lineno, "root": root,
                                    "heading": line.strip()[:60]})
    return entries, len(pages)


def order_violations(entries):
    """Where does the root sequence go backwards?

    Compared on alphabet POSITION, not on Python string order, because Hebrew
    final forms sort wrongly by codepoint and a root's letters are always
    non-final here.
    """
    def key(root):
        return tuple(ALEPHBET.index(c) if c in ALEPHBET else 99 for c in root)
    bad = []
    for prev, cur in zip(entries, entries[1:]):
        if key(cur["root"]) < key(prev["root"]):
            bad.append((prev, cur))
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layer-dir", required=True)
    ap.add_argument("--check-order", action="store_true")
    ap.add_argument("--out")
    ap.add_argument("--show", type=int, default=10)
    args = ap.parse_args()

    entries, npages = scan(os.path.expanduser(args.layer_dir))
    by_first = collections.Counter(e["root"][0] for e in entries)
    lens = collections.Counter(len(e["root"]) for e in entries)

    print(f"  pages scanned        {npages}")
    print(f"  entry headings found {len(entries)}")
    print(f"  root lengths         " +
          ", ".join(f"{k} letters: {v}" for k, v in sorted(lens.items())))
    print(f"  distinct initials    {len(by_first)} of 22")
    missing = [c for c in ALEPHBET if c not in by_first]
    if missing:
        print(f"  initials with NO entries: {' '.join(missing)}")
    print("\n  entries per initial letter (the 22 מאמרים)")
    print("   ", "  ".join(f"{c}:{by_first.get(c,0)}" for c in ALEPHBET))

    if args.show:
        print(f"\n  first {args.show} headings")
        for e in entries[:args.show]:
            print(f"    p{e['page']:<4} {e['root']:<6} {e['heading']}")

    if args.check_order:
        bad = order_violations(entries)
        print(f"\n  ALPHABETICAL ORDER CHECK")
        print(f"    violations {len(bad)} of {max(len(entries)-1,1)} adjacent pairs "
              f"({100.0*len(bad)/max(len(entries)-1,1):.1f}%)")
        for prev, cur in bad[:args.show]:
            print(f"      p{prev['page']:<4} {prev['root']:<6} -> "
                  f"p{cur['page']:<4} {cur['root']:<6}")
        if bad:
            print("    each is a missed heading, a false heading, or a printing"
                  " irregularity - all three need a human, none is auto-repairable")

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump({"pages_scanned": npages, "entries": entries}, fh,
                      ensure_ascii=False, indent=1)
            fh.flush(); os.fsync(fh.fileno())
        print(f"\n  wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
