#!/usr/bin/env python3
"""
tools/detect_root_entries.py

Find the entry headings of a root-dictionary, where each entry is headed by its
root SPELLED OUT AS LETTER NAMES.

THE STRUCTURE THIS EXISTS FOR. Sefer HaShorashim (Ibn Janah, tr. Ibn Tibbon, ed.
Bacher, Berlin 1896) has no gematria marker and no numbered sections, so
`pipeline/build_gematria_trace.py` has no analogue here. What it has instead is
better: every entry opens with its root written out as the NAMES of its letters,
terminated by a period -

    הבית והצדי והקוף.      = ב-צ-ק
    הבית והצדי והריש.      = ב-צ-ר

That is a closed 22-word vocabulary, so it is cheaper to detect than a gematria
marker. It is also SELF-CHECKING in a way a marker is not: the names spell the
root, and a dictionary's roots run in alphabetical order, so the detector's own
output can be validated against a rule the book must obey. `--check-order`
reports every position where the sequence goes backwards, and those are either a
missed heading, a false heading, or a genuine printing irregularity - all three
worth a human look, which is why it reports rather than repairs.

WHAT IT READS. Any directory of per-page plain text - by default the recovered
PDF text layer from `tools/extract_pdf_text_layer.py`, which for this book is
1,094,298 Hebrew characters over 636 pages at no API cost. That layer is Google
OCR and carries Google OCR's errors, so a heading it garbles is invisible here;
the order check is what surfaces the resulting gap.

ON OCR VARIANTS. `צרי` is accepted for `צדי` because the ד/ר confusion is this
printing's most common sort-level failure and it was observed in the layer on a
page whose ink was read directly. Variants are listed explicitly, never
generated by fuzzy matching: a fuzzy letter-name matcher would accept ordinary
running text that happens to be one edit away, and Lesson 5 (FUZZY IS NOT A
POSITION) is exactly about not doing that for a structural anchor.

Usage:
  python3 tools/detect_root_entries.py --layer-dir ~/work/hashorashim/google_books_layer
  python3 tools/detect_root_entries.py --layer-dir ... --check-order --out entries.json
"""

import argparse
import collections
import json
import os
import re
import sys

# Bootstrap only - deliberately NOT bound to a name like REPO, which is the
# seam bypass tests/test_pipeline_logic.py's bypass guard exists to catch. Every
# real path below goes through corpus_io, which resolves $SEFER_CORPUS_ROOT at
# call time.
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(os.path.dirname(_HERE), "pipeline"))
import corpus_io as cio  # noqa: E402

# The 22 letter names as this edition spells them, plus OCR variants ACTUALLY
# OBSERVED in the layer. Adding a variant is a claim about the printing; make it
# only after seeing it, and say which sort produced it.
# DISCOVERED FROM THE DATA, not written from knowledge of the alphabet. A
# hand-written list of the "obvious" 22 names found 840 headings and MISSED
# 1,147 - it had `ריש` for resh where this edition prints `רש`, so the entire
# ר מאמר (30 pages, PDF 509-538) came back empty and the alphabetical-order
# check did not notice, because a whole missing section produces no local
# inversion (ק -> ש is still forward). That is Lesson 26 THE FILTER THAT HIDES:
# the failure was silence, and the guard could not see it.
#
# These counts come from clustering every line-initial heading-SHAPED line in
# the recovered layer. Variants are kept separate from spellings on purpose:
LETTER_NAMES = {
    # the edition's own spellings
    "אלף": "א", "בית": "ב", "גימל": "ג", "דלת": "ד", "הא": "ה",
    "ואו": "ו", "זין": "ז", "חית": "ח", "טית": "ט", "יוד": "י",
    "כף": "כ", "למד": "ל", "מם": "מ", "נון": "נ", "סמך": "ס",
    "עין": "ע", "פא": "פ", "צדי": "צ", "קוף": "ק", "רש": "ר",
    "שין": "ש", "תו": "ת",
    # further spellings the edition itself uses, both attested in the layer
    "ריש": "ר", "תיו": "ת", "ויו": "ו", "וו": "ו", "חת": "ח", "טת": "ט",
    # printed once, p108 `הבית והואו והצירי.` (root בוץ): the same four letters
    # in the NLI photograph and in the Google copy, so it is the ink's spelling,
    # not an OCR variant - and not the vowel tsere, which QUALIFIERS once held it
    # to be (item 0GF)
    "צירי": "צ",
    # OCR variants, each with the sort that produced it
    "צרי": "צ",    # ד -> ר, this printing's commonest sort-level confusion - but
                   # also PRINTED so on p87 and p112 (both copies; item 0GJ), so
                   # a heading carrying it is a question for the ink, not an error
    "נימל": "ג",   # ג -> נ
}
# "the doubled one" - a geminate root, repeating the letter before it:
# `הרש וההא הכפולה` is ר-ה-ה. 152 occurrences; without it those entries are lost.
# `הכפול` is the same word in the masculine and does the same job (3 lines,
# e.g. p181 `הזין והלמד הכפול`); it is a spelling of DOUBLED, not a qualifier,
# and treating it as one would drop the repeated letter and mis-key the entry.
DOUBLED = "כפולה"
DOUBLED_FORMS = (DOUBLED, "כפול")

# QUALIFIERS - a word the edition puts AFTER the letter names to distinguish two
# entries that spell the same root.
#
# WHY THE DETECTOR MISSED THEM ENTIRELY. The heading pattern required the
# terminator to follow the last letter name directly, so a qualifier between the
# two made the line invisible. Measured cost: 46 headings book-wide, 7 inside the
# a-b-g slice - and because a missed heading does not end the previous entry, the
# text does not vanish, it MERGES. Our `אלל` (p79) ran to 987 words against the
# witness's 62, having swallowed both `אלה` entries whole. That is Lesson 26 THE
# FILTER THAT HIDES: the loss shows up as one fat entry, not as a gap.
#
# DISCOVERED FROM THE DATA by clustering every line whose letter-name run is
# complete but unterminated, then reading what follows. Counts across 651 pages:
#   עוד      35   "further" - a second entry for a root already given
#   הנראית    5   \ "the visible/pronounced one", three spellings of one word
#   הנראה     2   /  (`הנראת` is the OCR of `הנראית` with the yod lost)
#   הנראת     1   /
#   הרפה      2   \ "the soft one" - the unpointed/spirantized reading
#   הרפא      1   /
# Listed explicitly, never fuzzy-matched: a heading is a structural anchor and
# Lesson 5 FUZZY IS NOT A POSITION applies to it.
#
# `הצירי`, "the vowel tsere", was listed here with 1 occurrence until
# 2026-09-14. That occurrence is p108 `הבית והואו והצירי.` - the only
# heading-shaped `צירי` in either text layer - where it is the THIRD LETTER NAME
# of בוץ, with the list's vav in front of it, so the qualifier pattern could
# never match it and בוץ merged into בוס. It is a letter name now (item 0GF).
QUALIFIERS = ("עוד", "הנראית", "הנראת", "הנראה", "הרפה", "הרפא")

ALEPHBET = "אבגדהוזחטיכלמנסעפצקרשת"

def _spaced(name):
    r"""`פא` -> `פ[\s"'׳״]*א`. Two kinds of noise sit INSIDE a letter name.

    DocAI sometimes splits one across a space (`והפ א` for `והפא` on p135), which
    is tokenizer noise rather than a different reading - the ink says `והפא`.

    And the edition itself sets some names with an internal geresh or gershayim:
    p65 prints `האלף והואו והיו"ד`, and Sefaria's own transcription writes
    `אל'ף` and `בי'ת` throughout. One such line in this scan (p65, root אוי) was
    invisible to the detector, and a missed heading does not lose text - it
    MERGES it, so our `אוח` ran to 33 words against the witness's 12 by
    swallowing `אוי` whole.

    Neither widening loosens the three guards that actually carry the anchor: the
    match is still line-initial, still terminated, and still drawn from a closed
    22-word vocabulary."""
    return r"[\s\"'\u05f3\u05f4]*".join(name)


_NAME_ALT = "|".join(_spaced(n) for n in sorted(LETTER_NAMES, key=len, reverse=True))
_DOUBLED_ALT = "|".join(_spaced(n) for n in sorted(DOUBLED_FORMS, key=len, reverse=True))
_QUAL_ALT = "|".join(_spaced(q) for q in sorted(QUALIFIERS, key=len, reverse=True))
# A heading is LINE-INITIAL and ends with a period or comma. Both halves matter:
# the same letter-name words appear constantly inside running prose (the book is
# about letters), and only the line-initial + terminator shape is the heading.
#
# "Line-initial" means THE FIRST HEBREW LETTER ON THE LINE, not the first
# character. Widened 2026-09-09 after the DocAI stream lost 21 of 308 headings in
# the א-ב-ג slice that the PDF text layer found - every one of them real, and
# every one preceded by a footnote numeral or a bracket that the two OCRs place
# differently:
#     p59    17 האלף והבית והכף . ויתאבכו גאות עשן
#     p109   88 הבית והזין הכפולה , בחזו להם ישראל
#     p146   [ הנימל והעין וההא , יגעה שור
# The anchor is not weakened by this: the first Hebrew letter must still open the
# heading, the terminator is still required, and the letter-name vocabulary is
# still closed.
#
# A PERIOD MAY FOLLOW THE FIRST NAME. p148 prints `הגימל. והרש והבית.` and p585
# `השין. והרש והפא.` - read off the ink of the NLI photograph and the Google
# copy, not inferred from the OCR. Requiring the second name straight after the
# first made both invisible (גרב merged into גרר; שרפ was never listed). Swept
# over both text layers and the DocAI stream: the widening adds exactly those
# two headings and changes no existing match (item 0GF).
HEADING = re.compile(
    rf"^[^\u05d0-\u05ea]*ה(?P<first>{_NAME_ALT})"
    rf"\s*\.?(?P<rest>(?:\s+ו?ה(?:{_NAME_ALT}|{_DOUBLED_ALT})){{1,4}})"
    rf"(?P<qual>\s+(?:{_QUAL_ALT}))?\s*[.,]"
)
NAME_IN_REST = re.compile(rf"ו?ה({_NAME_ALT}|{_DOUBLED_ALT})")


def match_heading(line):
    """(root, end_offset) for a heading line, or None.

    The END OFFSET matters: headings terminate with a period OR a comma, and
    splitting on `line.find(".")` instead swallows the whole entry into the title
    whenever the terminator is a comma. That produced 8 empty entries out of 299
    on the first build - `האלף והנימל , אבל זה הוא...` kept everything.
    """
    m = HEADING.match(line)
    if not m:
        return None
    root = _letters_from(m)
    return (root, m.end()) if root else None


def parse_heading(line):
    m = HEADING.match(line)
    if not m:
        return None
    return _letters_from(m)


def _letters_from(m):
    # Strip whatever _spaced() was widened to tolerate, so the squashed form is
    # a key in the closed vocabulary. Keeping these two in step matters: widening
    # the pattern without widening this raises KeyError on the very lines the
    # widening was meant to recover.
    squash = lambda x: re.sub(r"[\s\"'\u05f3\u05f4]+", "", x)
    letters = [LETTER_NAMES[squash(m.group("first"))]]
    for n in NAME_IN_REST.findall(m.group("rest")):
        if squash(n) in DOUBLED_FORMS:
            if not letters:
                return None
            letters.append(letters[-1])   # geminate: repeat the preceding letter
        else:
            letters.append(LETTER_NAMES[squash(n)])
    return "".join(letters)


# SPELLINGS THE MATCHER TOLERATES that are NOT the names of letters, with the name
# each stands for (item 0GJ). Kept in LETTER_NAMES so an entry boundary is not
# lost; flagged by heading_concerns() because the stored heading needs the ink.
# NOT always an OCR error: `צרי` is PRINTED on p87 (`האלף והמם והצרי.`) and p112
# (`הבית והיוד והצרי.`) - resh in both the NLI photograph and the Google copy -
# while p120 prints `הבית והצדי והעין.` and DocAI read `צרי` there too. The
# concern says the ink decides; it does not say which way.
OCR_VARIANTS = {"צרי": "צדי", "נימל": "גימל"}


def heading_concerns(title, root=None):
    """Why this heading is not simply the root's letters spelled out; [] if it is.

    Reviewer 2026-09-14: "any time those three words are not the name of three
    letters, we have a concern". Every word of the heading must be a letter name
    in the edition's own spellings, the doubling word (`הכפולה`), or a qualifier
    the edition uses to part homographs (`עוד`, `הנראית`...). An OCR misreading
    the matcher tolerates (`צרי` for `צדי`) is a concern: it is not a letter's
    name. `root`, when given, must be what the names spell.
    """
    hit = match_heading(title or "")
    if not hit:
        return ["The heading does not read as the names of letters."]
    out = []
    words = [cio.hebrew_letters_only(w) for w in title[:hit[1]].split()]
    for i, w in enumerate(x for x in words if x):
        if w in QUALIFIERS:
            continue
        core = re.sub(r"^ו?ה", "", w) if i else re.sub(r"^ה", "", w)
        if core in DOUBLED_FORMS:
            continue
        if core in OCR_VARIANTS:
            out.append(f"`{w}` is not the name of a letter (the name is "
                       f"`{OCR_VARIANTS[core]}`): the OCR may have misread it, or the page "
                       f"may print it so - the ink decides.")
        elif core not in LETTER_NAMES:
            out.append(f"`{w}` is not the name of a letter.")
    if root and cio.root_key(hit[0]) != cio.root_key(root):
        out.append(f"The names spell `{hit[0]}`, not this entry's root `{root}`.")
    return out


def scan(layer_dir):
    entries = []
    pages = sorted(
        (int(re.search(r"page_(\d+)\.txt$", f).group(1)), os.path.join(layer_dir, f))
        for f in os.listdir(layer_dir) if re.match(r"page_\d+\.txt$", f))
    for page, path in pages:
        with open(path, encoding="utf-8") as fh:
            for lineno, line in enumerate(fh.read().split("\n"), start=1):
                root = parse_heading(line)
                if root:
                    entries.append({"page": page, "line": lineno, "root": root,
                                    "heading": line.strip()[:60]})
    return entries, len(pages)


def root_order_key(root):
    """Where a root falls in the book's own order.

    Compared on alphabet POSITION, not on Python string order, because Hebrew
    final forms sort wrongly by codepoint and a root's letters are always
    non-final here.

    Plain alphabetical order is not the book's order. Measured on Sefer
    HaShorashim 2026-09-14 (pipeline item 0GM), 16 of the 17 "violations" plain
    order found were the arrangement itself:
    * a chapter opens with `X הכפולה` (`בב`, `גג`), ahead of `באר`;
    * a two-letter section heading (`אג`, `בד`) opens its group;
    * within a group the doubled root comes first (`אלל` before `אלה`, `ברר`
      before `ברא`).
    With that encoded, 1 of 318 headings was out of order, and it was a false
    heading (entry 16, `אג`, running text after `אגמ`)."""
    pos = lambda c: ALEPHBET.index(c) if c in ALEPHBET else 99
    if len(root) < 2:
        return tuple(pos(c) for c in root)
    if len(root) == 2 and root[1] == root[0]:
        return (pos(root[0]), -1)
    rank = 0 if len(root) == 2 else (1 if root[2] == root[1] else 2)
    return (pos(root[0]), pos(root[1]), rank) + tuple(pos(c) for c in root[2:])


def order_violations(entries):
    """Where does the root sequence go backwards, in the book's own order?"""
    bad = []
    for prev, cur in zip(entries, entries[1:]):
        if root_order_key(cur["root"]) < root_order_key(prev["root"]):
            bad.append((prev, cur))
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layer-dir", required=True)
    ap.add_argument("--check-order", action="store_true")
    ap.add_argument("--out")
    ap.add_argument("--show", type=int, default=10)
    args = ap.parse_args()

    entries, npages = scan(os.path.expanduser(args.layer_dir))
    by_first = collections.Counter(e["root"][0] for e in entries)
    lens = collections.Counter(len(e["root"]) for e in entries)

    print(f"  pages scanned        {npages}")
    print(f"  entry headings found {len(entries)}")
    print(f"  root lengths         " +
          ", ".join(f"{k} letters: {v}" for k, v in sorted(lens.items())))
    print(f"  distinct initials    {len(by_first)} of 22")
    missing = [c for c in ALEPHBET if c not in by_first]
    if missing:
        print(f"  initials with NO entries: {' '.join(missing)}")
    print("\n  entries per initial letter (the 22 מאמרים)")
    print("   ", "  ".join(f"{c}:{by_first.get(c,0)}" for c in ALEPHBET))

    if args.show:
        print(f"\n  first {args.show} headings")
        for e in entries[:args.show]:
            print(f"    p{e['page']:<4} {e['root']:<6} {e['heading']}")

    if args.check_order:
        bad = order_violations(entries)
        print(f"\n  ALPHABETICAL ORDER CHECK")
        print(f"    violations {len(bad)} of {max(len(entries)-1,1)} adjacent pairs "
              f"({100.0*len(bad)/max(len(entries)-1,1):.1f}%)")
        for prev, cur in bad[:args.show]:
            print(f"      p{prev['page']:<4} {prev['root']:<6} -> "
                  f"p{cur['page']:<4} {cur['root']:<6}")
        if bad:
            print("    each is a missed heading, a false heading, or a printing"
                  " irregularity - all three need a human, none is auto-repairable")

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump({"pages_scanned": npages, "entries": entries}, fh,
                      ensure_ascii=False, indent=1)
            fh.flush(); os.fsync(fh.fileno())
        print(f"\n  wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
