#!/usr/bin/env python3
"""
tools/list_cross_edition_disputes.py

[STANDALONE] A reviewer's worklist of the disputes the CROSS-EDITION witness
takes part in, as dashboard links grouped by what each group is worth.

Written 2026-09-04, reviewer: "can I filter on this? provide a md list of urls".
The answer to the first half is no - the dashboard's nav has only the Flagged
and High-value checkboxes, and the cross-edition fields are served but have no
control bound to them. This is the second half, and it is a GENERATOR rather
than a file someone types once: corrections_part1.json is rewritten wholesale by
every ./rebuild_all.sh, so a hand-maintained list of word indices would be
silently wrong the first time the queue moved (CLAUDE.md Lesson 13).

Reads corrections_part1.json only. Writes one markdown file. Records nothing,
decides nothing, and touches no corpus text.

The three groups, in the order a reviewer should spend attention on them:

  1. RESTORE AN ABBREVIATION - the consensus reads a geresh where the corpus
     stored a letter (usually a yod). Item 0AQ's own defect, found
     systematically. These are real correction candidates and most do not
     depend on the cross-edition witness at all.
  2. EXPAND AN ABBREVIATION - the consensus spells out a word the corpus
     abbreviates. Item 0AQ ruled the Berlin abbreviation is what the corpus
     keeps, so the expected outcome is CONFIRMING the stored text, not changing
     it. Listed so they get looked at and closed, not so they get applied.
  3. ONE ENGINE READ THIS INK - a cross-edition consensus where only a single
     engine that read the Berlin scan differs from the corpus. The largest
     group by far, and the weakest: a genuine difference between the printings
     is a live explanation for every one of them.

Usage:
  python3 tools/list_cross_edition_disputes.py
  python3 tools/list_cross_edition_disputes.py --out /tmp/worklist.md --limit 40
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INSTALL_DIR = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(INSTALL_DIR, "pipeline"))

import corpus_io as cio  # noqa: E402

DEFAULT_BASE = "http://127.0.0.1:8420"
OUT_PATH = cio.repo_path("CROSS-EDITION-WORKLIST.md")


def rows():
    """Every cross-edition-marked or abbreviation-shaped candidate, flat."""
    by_klal = cio.load_json(cio.repo_path("corrections_part1.json"), {}) or {}
    out = []
    for kid_str, items in by_klal.items():
        for c in items:
            if c.get("cross_edition") or c.get("abbreviation_shape"):
                c = dict(c)
                c["klal_id"] = int(kid_str)
                out.append(c)
    out.sort(key=lambda c: (c["klal_id"], c.get("word_index") or 0))
    return out


def _line(c, base):
    engines = "+".join(c.get("consensus_engines") or [])
    n = c.get("same_edition_agreeing")
    ink = (f"{n} engine read this ink" if n == 1
           else f"{n} engines read this ink" if n is not None else "")
    return (f"- [klal {c['klal_id']} · word {c['word_index']}]"
            f"({base}/klal/{c['klal_id']}/word/{c['word_index']}) — "
            f"corpus `{c.get('final_text')}` → `{c.get('consensus_reading')}` "
            f"({engines}{', ' + ink if ink else ''})")


def build(base=DEFAULT_BASE, limit=None):
    all_rows = rows()
    restore = [c for c in all_rows
               if c.get("abbreviation_shape") == "consensus_abbreviates"]
    expand = [c for c in all_rows
              if c.get("abbreviation_shape") == "consensus_expands"]
    shaped = {id(c) for c in restore} | {id(c) for c in expand}
    thin = [c for c in all_rows
            if id(c) not in shaped and c.get("cross_edition")
            and c.get("same_edition_agreeing") == 1]
    thick = [c for c in all_rows
             if id(c) not in shaped and c.get("cross_edition")
             and c.get("same_edition_agreeing") != 1]

    L = ["# Cross-edition worklist",
         "",
         "Generated by `tools/list_cross_edition_disputes.py` from "
         "`corrections_part1.json` — **regenerate it after any rebuild**, the "
         "word indices move.",
         "",
         "The dashboard has no filter for these (its nav offers only Flagged "
         "and High-value), so this file is the filter. Links open the review "
         "server: `python3 pipeline/review_server.py`.",
         "",
         "`dicta` reads the **Jerusalem 1975/6** printing, not the Berlin scan "
         "this corpus transcribes. Its agreement is real evidence — a different "
         "compositor setting the same text — but it is not a second look at "
         "this ink, so a disagreement it takes part in has one explanation the "
         "same-edition engines never have: the two printings simply differ.",
         ""]

    def section(title, items, blurb):
        L.append(f"## {title} ({len(items)})")
        L.append("")
        L.append(blurb)
        L.append("")
        shown = items if limit is None else items[:limit]
        L.extend(_line(c, base) for c in shown)
        if len(shown) < len(items):
            L.append(f"- …and {len(items) - len(shown)} more (raise `--limit`)")
        L.append("")

    section("Restore an abbreviation the corpus spelled out", restore,
            "**Look at these first.** The consensus reads an abbreviation mark "
            "where the corpus stored a letter — nearly always the geresh read "
            "as a **yod**, so `מה׳` is stored as `מהי`. This is item 0AQ's own "
            "defect found systematically, these are real correction candidates, "
            "and most were already found by the two Berlin engines alone. Fast "
            "to confirm against the ink because you know exactly what to look "
            "for.")
    section("Expand an abbreviation the corpus stores", expand,
            "**The expected outcome here is CONFIRMING the stored text.** The "
            "consensus would spell out a word the corpus abbreviates. Item 0AQ "
            "ruled the Berlin abbreviation is what the corpus keeps — the "
            "reviewer restored `ומתי׳` over the editorial `ומתיר` — so if the "
            "ink shows the mark, the stored text is already right. Listed so "
            "they get closed, not so they get applied.")
    section("Cross-edition, and only ONE engine read this ink", thin,
            "The weakest group, and the largest. A single Berlin-reading engine "
            "differs from the corpus and the cross-edition witness agrees with "
            "it. That is genuine evidence, but a real difference between the "
            "two printings explains every one of these equally well, so the "
            "scan decides and nothing here should be taken on the engine count.")
    section("Cross-edition, with two or more engines on this ink", thick,
            "Two engines that read the Berlin scan already dissent; the "
            "cross-edition witness is corroborating a consensus that stands "
            "without it. Strongest of the cross-edition groups.")

    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=OUT_PATH)
    ap.add_argument("--base-url", default=DEFAULT_BASE)
    ap.add_argument("--limit", type=int, default=None,
                    help="cap each section (default: list everything)")
    args = ap.parse_args()

    md = build(args.base_url.rstrip("/"), args.limit)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(md)
        f.flush()
    print(f"Wrote {args.out}")
    for line in md.split("\n"):
        if line.startswith("## "):
            print(f"  {line[3:]}")


if __name__ == "__main__":
    main()
